server:
  mode: debug
  port: 3001
mongodb:
  host: localhost
  port: 27017
  username: admin
  password: secret
  database: chatbot_database
  collection:
    token: token
    user: user
    chatbot: chatbot
    client: client
    chat_history: chat_history
  max_pool_size: 10
  connect_timeout: 5
  auth_source: admin
logger:
  dir: log
  file_name: belajar-architecture-jatis
  max_backups: 0 # set 0 for unlimited backups
  max_size: 10 # in mb
  max_age: 90 # in days, set 0 for unlimited days
  compress: true
  local_time: true
chatbot:
  welcome_message: welcome_message
  submit_crd_message: submit_crd_message
  additional_point: 10
  success_submit_crd: Terima kasih terlah submit kode crd, point anda saat ini
  failed_request: Maaf kami tidak mengerti
