server:
  mode: debug
  port: 3001
mongodb:
  host: localhost
  port: 27017
  username: admin
  password: secret
  database: chatbot_database
  collection:
    token: token
    user: user
    chatbot: chatbot
    client: client
    chat_history: chat_history
  max_pool_size: 10
  connect_timeout: 5
  auth_source: admin
logger:
  dir: log
  file_name: belajar-architecture-jatis
  max_backups: 0 # set 0 for unlimited backups
  max_size: 10 # in mb
  max_age: 90 # in days, set 0 for unlimited days
  compress: true
  local_time: true
chatbot_message:
  welcome: welcome_message
  submit_crd: submit_crd_message
